### PR TITLE
Adapting coffea-casa Docker image for compatibility with JupyterHub at the ElasticAF

### LINKED ISSUE #109: Change from 'jovyan' to 'cms-jovyan' needs to be applied to the start.sh script
Hi CoffeaCasa team,

I am trying to deploy the coffea-casa Docker image in our Kubernetes (OKD4 cluster) over at FNAL. 

Jupyter developers designed this 'placeholder' jovyan user with the idea of giving a configurable path to possibly creating local system users.

Long story short, I was able to deploy notebooks running as the logged user's userame instead of jovyan, but this is not possible for the coffea-casa notebooks if the start shell scripts are not ported correctly to this new jovyan-cms user. I would suggest searching and replacing `jovyan` with `cms-jovyan` on the script at `coffea-casa/blob/master/docker/coffea-casa/start.sh` and  then we can go from there

### PR DESCRIPTION
**Pull request by mapsacosta**
Fixes #109

### CODE REVIEW

**Comment by mapsacosta** [comment]
CC. @holzman

**Comment by oshadura** [comment]
@mapsacosta thanks a lot for the fixes!

**Review by oshadura — APPROVED** [review]
LGTM!

**Comment by oshadura** [comment]
@mapsacosta I am merging your patch and will publish now both images with 2021.04.27 tag

**Pull request merged**
